import requests
import json
import os
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(__file__), '..', '..', 'copperbuilds.env'))

USERNAME = os.getenv('DATAFORSEO_USERNAME')
PASSWORD = os.getenv('DATAFORSEO_PASSWORD')

KEYWORDS = [
    # ==========================================================
    # BLOCK 1: EXISTING BLOG POST ROOTS + CLUSTER VARIANTS (~90)
    # ==========================================================
    # contractor website
    "contractor website",
    "contractor website design",
    "contractor web design",
    "contractor website cost",
    "website for contractors",
    "contractor website not ranking",
    "contractor website seo",
    "best contractor website",
    "contractor website builder",
    "contractor website template",
    # web designer
    "web designer for small business",
    "hire web designer",
    "web designer cost",
    "how to choose web designer",
    "web design agency small business",
    "web designer near me",
    "web design for trade business",
    "best web designer small business",
    "find web designer",
    "freelance web designer",
    # google reviews
    "google reviews for business",
    "get google reviews",
    "how to get google reviews",
    "google review management",
    "increase google reviews",
    "google review strategy",
    "more google reviews",
    "google review request",
    "google reviews small business",
    "google business reviews",
    # website cost
    "small business website cost",
    "website cost",
    "website design cost",
    "how much does a website cost",
    "website pricing",
    "web design cost small business",
    "website design price",
    "affordable website design",
    "business website cost",
    "website development cost",
    # website vs facebook
    "website vs facebook page",
    "do i need a website",
    "website vs social media",
    "business website vs facebook",
    "facebook page vs website",
    "social media vs website for business",
    "do i need a website or facebook page",
    # website conversion
    "website conversion",
    "website not converting",
    "website conversion rate",
    "increase website conversions",
    "website not getting leads",
    "website lead generation",
    "website calls",
    "website getting traffic but no leads",
    "local business website conversion",
    "improve website conversion rate",
    # google maps ranking
    "google maps ranking",
    "rank google maps",
    "google maps seo",
    "google map pack ranking",
    "google maps optimization",
    "rank on google maps",
    "google maps local seo",
    "google maps 3 pack",
    "google maps 3 pack ranking",
    "local map pack seo",
    # local seo
    "local seo",
    "local seo tips",
    "local seo strategy",
    "local search optimization",
    "local seo for small business",
    "local seo guide",
    "local business seo",
    "local seo services",
    "local seo company",
    "local seo agency",

    # ==========================================================
    # BLOCK 2: 4 NEW BLOG TOPICS + CLUSTER VARIANTS (~80)
    # ==========================================================
    # Blog 1: hvac seo
    "hvac seo",
    "seo for hvac companies",
    "hvac local seo",
    "hvac seo services",
    "hvac seo agency",
    "hvac website ranking",
    "hvac google ranking",
    "hvac google maps ranking",
    "hvac seo tips",
    "hvac seo strategy",
    "hvac seo company",
    "hvac search engine optimization",
    "hvac company seo",
    "best hvac seo",
    # Blog 2: hvac website design
    "hvac website design",
    "hvac web design",
    "hvac company website",
    "hvac website",
    "hvac website cost",
    "best hvac website design",
    "hvac website examples",
    "hvac landing page",
    "hvac website builder",
    "hvac website template",
    "hvac company website design",
    "hvac contractor website",
    "hvac web design cost",
    # Blog 3: hvac marketing
    "hvac marketing",
    "hvac marketing strategy",
    "hvac marketing ideas",
    "hvac lead generation",
    "hvac marketing tips",
    "hvac advertising",
    "hvac digital marketing",
    "hvac marketing agency",
    "hvac marketing company",
    "hvac online marketing",
    "hvac customer acquisition",
    "how to market hvac business",
    "hvac business marketing",
    "hvac social media marketing",
    "hvac google ads",
    "hvac ppc advertising",
    "hvac content marketing",
    "hvac email marketing",
    # Blog 4: contractor seo
    "contractor seo",
    "seo for contractors",
    "contractor search engine optimization",
    "contractor local seo",
    "contractor google ranking",
    "contractor seo services",
    "contractor seo agency",
    "home contractor seo",
    "contractor digital marketing",
    "contractor marketing",
    "contractor lead generation",
    "how to get contractor leads",
    "contractor seo company",
    "best contractor seo",

    # ==========================================================
    # BLOCK 3: COPPERBUILDS SERVICE KEYWORDS (~70)
    # ==========================================================
    # Web design services
    "web design for small business",
    "small business web design",
    "local business website design",
    "small business website",
    "website design for home service business",
    "home service website design",
    "trades web design",
    "professional website small business",
    "web design agency for contractors",
    "affordable web design small business",
    "web design agency home services",
    "website design agency small business",
    "web design for home services",
    "website for home service company",
    "home services web design",
    # Local SEO services
    "local seo services small business",
    "local seo packages",
    "affordable local seo",
    "local seo for home service",
    "local seo marketing agency",
    "local seo management",
    "local seo optimization services",
    "local seo for contractors",
    "local seo company for contractors",
    "best local seo agency",
    # Google Business Profile
    "google business profile setup",
    "google my business setup",
    "google business profile optimization",
    "google business profile management",
    "google my business optimization",
    "set up google business profile",
    "google business listing",
    "google business profile service",
    "gbp optimization",
    # Agency/general
    "web design agency home services",
    "web agency small business",
    "website design agency",
    "web design company small business",
    "home services marketing agency",
    "digital marketing for home services",
    "marketing agency for contractors",
    "home service digital marketing agency",
    "trade business marketing",
    "contractor marketing agency",
    # Website design types
    "mobile friendly website design",
    "responsive website design small business",
    "fast website small business",
    "seo friendly website design",
    "conversion optimized website",
    "landing page design small business",
    "lead generation website design",
    "professional website design",
    "custom website design small business",

    # ==========================================================
    # BLOCK 4: HVAC — DEEP KEYWORD SET (~120)
    # ==========================================================
    # HVAC leads
    "hvac leads",
    "buy hvac leads",
    "hvac lead generation services",
    "hvac lead gen",
    "exclusive hvac leads",
    "hvac leads online",
    "hvac leads for contractors",
    "get hvac leads",
    # HVAC reputation/reviews
    "hvac reputation management",
    "hvac online reviews",
    "hvac google reviews",
    "hvac customer reviews",
    "hvac review management",
    # HVAC branding
    "hvac company branding",
    "hvac brand identity",
    "hvac company name",
    "hvac logo design",
    # HVAC business growth
    "how to grow hvac business",
    "hvac business growth",
    "hvac business tips",
    "hvac company growth strategy",
    "scale hvac business",
    "hvac company success",
    "hvac contractor success",
    # HVAC by city — US major markets
    "hvac houston",
    "hvac companies houston tx",
    "hvac contractor houston",
    "hvac houston tx",
    "hvac repair houston",
    "hvac installation houston",
    "hvac atlanta",
    "hvac companies atlanta",
    "hvac atlanta ga",
    "hvac repair atlanta",
    "hvac miami",
    "hvac companies miami fl",
    "hvac miami fl",
    "hvac repair miami",
    "hvac chicago",
    "hvac companies chicago il",
    "hvac chicago il",
    "hvac repair chicago",
    "hvac denver",
    "hvac companies denver co",
    "hvac denver co",
    "hvac repair denver",
    "hvac las vegas",
    "hvac companies las vegas nv",
    "hvac las vegas nv",
    "hvac phoenix",
    "hvac companies phoenix az",
    "hvac phoenix az",
    "hvac austin tx",
    "hvac companies austin texas",
    "hvac repair austin",
    "hvac san antonio tx",
    "hvac companies san antonio",
    "hvac repair san antonio",
    "hvac charlotte nc",
    "hvac companies charlotte nc",
    "hvac repair charlotte",
    "hvac nashville tn",
    "hvac companies nashville",
    "hvac repair nashville",
    "hvac orlando fl",
    "hvac companies orlando fl",
    "hvac repair orlando",
    "hvac tampa fl",
    "hvac companies tampa",
    "hvac repair tampa",
    "hvac seattle wa",
    "hvac companies seattle",
    "hvac minneapolis mn",
    "hvac companies minneapolis",
    "hvac kansas city",
    "hvac companies kansas city",
    "hvac raleigh nc",
    "hvac companies raleigh",
    "hvac jacksonville fl",
    "hvac companies jacksonville",
    "hvac indianapolis",
    "hvac companies indianapolis",
    "hvac columbus ohio",
    "hvac companies columbus ohio",
    "hvac san diego",
    "hvac companies san diego",
    "hvac portland or",
    "hvac companies portland oregon",
    "hvac sacramento",
    "hvac companies sacramento",

    # ==========================================================
    # BLOCK 5: ROOFING — DEEP KEYWORD SET (~100)
    # ==========================================================
    # Roofing web/marketing
    "roofing website design",
    "roofing web design",
    "roofer website design",
    "roofing company website",
    "roofing website cost",
    "roofing seo",
    "roofer seo",
    "seo for roofing companies",
    "roofing local seo",
    "roofing google maps",
    "roofing marketing",
    "roofer marketing",
    "roofing marketing agency",
    "roofing lead generation",
    "roofing leads",
    "buy roofing leads",
    "roofing digital marketing",
    "roofing advertising",
    "roofing google ads",
    "roofing ppc",
    "roofing online marketing",
    "roofing reputation management",
    "roofing google reviews",
    "roofing content marketing",
    "how to grow roofing business",
    "roofing company branding",
    "roofing contractor website",
    "roofing contractor seo",
    "storm damage roofing leads",
    "roofing company marketing ideas",
    "roofing lead gen",
    "exclusive roofing leads",
    "roofing company marketing",
    "roofing business growth",
    "scale roofing business",
    "roofing email marketing",
    "roofing social media marketing",
    "roofing company google ranking",
    "best roofing website",
    "roofing website examples",
    # Roofing by city
    "roofing companies houston tx",
    "roofing contractor houston",
    "roofing companies atlanta ga",
    "roofing companies miami fl",
    "roofing companies chicago il",
    "roofing companies dallas tx",
    "roofing companies phoenix az",
    "roofing companies denver co",
    "roofing companies charlotte nc",
    "roofing companies nashville tn",
    "roofing companies orlando fl",
    "roofing companies tampa fl",
    "roofing companies raleigh nc",
    "roofing companies san antonio tx",

    # ==========================================================
    # BLOCK 6: PLUMBING — DEEP KEYWORD SET (~100)
    # ==========================================================
    # Plumbing web/marketing
    "plumber website design",
    "plumbing website design",
    "plumber web design",
    "plumbing company website",
    "plumber website cost",
    "plumber seo",
    "plumbing seo",
    "seo for plumbers",
    "plumbing local seo",
    "plumber google maps",
    "plumber marketing",
    "plumbing marketing",
    "plumbing marketing agency",
    "plumber lead generation",
    "plumbing leads",
    "buy plumbing leads",
    "plumbing digital marketing",
    "plumber advertising",
    "plumber google ads",
    "plumbing ppc",
    "plumbing online marketing",
    "plumber reputation management",
    "plumber google reviews",
    "plumbing content marketing",
    "how to grow plumbing business",
    "plumbing company branding",
    "plumbing contractor website",
    "plumbing contractor seo",
    "emergency plumber marketing",
    "plumbing company marketing ideas",
    "plumber lead gen",
    "exclusive plumbing leads",
    "plumbing company marketing",
    "plumbing business growth",
    "scale plumbing business",
    "plumber social media marketing",
    "plumber email marketing",
    "plumbing company google ranking",
    "best plumber website",
    "plumber website examples",
    # Plumbing by city
    "plumber houston tx",
    "plumbing companies houston",
    "plumber atlanta ga",
    "plumbing companies atlanta",
    "plumber miami fl",
    "plumbing companies miami",
    "plumber chicago il",
    "plumbing companies chicago",
    "plumber dallas tx",
    "plumbing companies dallas",
    "plumber phoenix az",
    "plumbing companies phoenix",
    "plumber denver co",
    "plumbing companies denver",
    "plumber charlotte nc",
    "plumbing companies charlotte",
    "plumber nashville tn",
    "plumber orlando fl",
    "plumber tampa fl",
    "plumber san antonio tx",

    # ==========================================================
    # BLOCK 7: FUTURE BLOG SEEDS + HOME SERVICE GENERAL (~80)
    # ==========================================================
    "home service marketing",
    "home service lead generation",
    "home service digital marketing",
    "marketing for home service businesses",
    "home improvement marketing",
    "contractor advertising ideas",
    "contractor online presence",
    "contractor branding",
    "local business marketing",
    "small business online marketing",
    "google local service ads",
    "local service ads contractors",
    "google guaranteed contractor",
    "google lsa for hvac",
    "google lsa for plumbers",
    "google lsa for roofers",
    "online reputation management contractors",
    "manage online reviews business",
    "website speed small business",
    "mobile website small business",
    "social media for contractors",
    "contractor social media marketing",
    "email marketing for contractors",
    "video marketing contractors",
    "content marketing for contractors",
    "contractor blog ideas",
    "how to get more customers contractor",
    "how to grow contracting business",
    "home service business growth",
    "best marketing for contractors",
    "contractor business tips",
    "contractor online marketing",
    # SEO/web fundamentals for blogs
    "seo for small business",
    "small business seo",
    "seo tips small business",
    "website traffic small business",
    "how to rank on google",
    "get on first page google",
    "google ranking tips",
    "seo basics small business",
    "on page seo guide",
    "technical seo small business",
    "google algorithm update",
    "core web vitals",
    "page speed seo",
    "mobile seo",
    "schema markup small business",
    "structured data seo",
    "internal linking seo",
    "backlinks small business",
    "link building small business",
    "citation building local seo",
    "nap consistency seo",
    "local citations seo",
    "directory listings local seo",
    "yelp for business",
    "angi leads",
    "homeadvisor leads",
    "thumbtack for contractors",
    "nextdoor for business",
    # Web design conversion
    "call to action website",
    "website trust signals",
    "social proof website",
    "testimonials website",
    "website chat widget",
    "click to call website",
    "website contact form",
    "website booking system",
    "online scheduling small business",
    "appointment booking website",

    # ==========================================================
    # BLOCK 8: ELECTRICAL + LANDSCAPING + PEST (to 1000)
    # ==========================================================
    # Electrical
    "electrician website design",
    "electrician web design",
    "electrician seo",
    "seo for electricians",
    "electrician marketing",
    "electrician lead generation",
    "electrician leads",
    "electrician digital marketing",
    "electrician google ads",
    "electrician local seo",
    "electrician google maps",
    "electrician marketing agency",
    "electrician website cost",
    "electrician company website",
    "how to grow electrical business",
    # Landscaping
    "landscaping website design",
    "landscaper website design",
    "landscaping seo",
    "landscaping marketing",
    "landscaping lead generation",
    "landscaping leads",
    "landscaping digital marketing",
    "landscaper marketing",
    "landscaping google ads",
    "landscaping local seo",
    "landscaping company website",
    "landscaping company marketing",
    "lawn care website design",
    "lawn care marketing",
    "lawn care leads",
    # Pest control
    "pest control website design",
    "pest control seo",
    "pest control marketing",
    "pest control lead generation",
    "pest control leads",
    "pest control digital marketing",
    "pest control google ads",
    "pest control local seo",
    "pest control company website",
    "pest control marketing agency",
    # Painting
    "painting contractor website design",
    "painting contractor seo",
    "painting contractor marketing",
    "painting contractor leads",
    "painter website design",
    "painter marketing",
    "house painter marketing",
    "painting company website",
    "painting company marketing",
    "painting contractor digital marketing",
    # Cleaning
    "cleaning company website design",
    "cleaning service website design",
    "cleaning business seo",
    "cleaning business marketing",
    "cleaning business lead generation",
    "cleaning service marketing",
    "maid service website design",
    "janitorial service marketing",
    "commercial cleaning marketing",
    "residential cleaning marketing",
    # General trades
    "trade business website design",
    "trade business marketing",
    "trade business seo",
    "trade company website",
    "home services seo",
    "home services marketing company",
    "marketing for trades",
    "trades marketing agency",
    "service business website design",
    "service business marketing",

    # ==========================================================
    # BLOCK 9: HVAC — AIR CONDITIONING + HEATING VARIANTS (~100)
    # ==========================================================
    "air conditioning company marketing",
    "ac company marketing",
    "air conditioning seo",
    "ac company seo",
    "ac repair marketing",
    "air conditioning website design",
    "ac company website design",
    "air conditioning company website",
    "ac installation leads",
    "ac repair leads",
    "air conditioning leads",
    "heating company marketing",
    "furnace company marketing",
    "heating seo",
    "heating company website design",
    "hvac contractor marketing",
    "hvac installation leads",
    "hvac repair leads",
    "hvac tune up leads",
    "hvac maintenance leads",
    # HVAC city — additional US markets
    "hvac albuquerque nm",
    "hvac companies albuquerque",
    "hvac baton rouge la",
    "hvac companies baton rouge",
    "hvac birmingham al",
    "hvac companies birmingham",
    "hvac buffalo ny",
    "hvac companies buffalo",
    "hvac cincinnati oh",
    "hvac companies cincinnati",
    "hvac cleveland oh",
    "hvac companies cleveland",
    "hvac colorado springs co",
    "hvac companies colorado springs",
    "hvac el paso tx",
    "hvac companies el paso",
    "hvac fort worth tx",
    "hvac companies fort worth",
    "hvac fresno ca",
    "hvac companies fresno",
    "hvac greensboro nc",
    "hvac companies greensboro",
    "hvac hartford ct",
    "hvac companies hartford",
    "hvac honolulu hi",
    "hvac companies honolulu",
    "hvac jersey city nj",
    "hvac companies jersey city",
    "hvac louisville ky",
    "hvac companies louisville",
    "hvac memphis tn",
    "hvac companies memphis",
    "hvac mesa az",
    "hvac companies mesa",
    "hvac new orleans la",
    "hvac companies new orleans",
    "hvac newark nj",
    "hvac companies newark",
    "hvac norfolk va",
    "hvac companies norfolk",
    "hvac oklahoma city ok",
    "hvac companies oklahoma city",
    "hvac omaha ne",
    "hvac companies omaha",
    "hvac pittsburgh pa",
    "hvac companies pittsburgh",
    "hvac richmond va",
    "hvac companies richmond",
    "hvac riverside ca",
    "hvac companies riverside",
    "hvac salt lake city ut",
    "hvac companies salt lake city",
    "hvac st louis mo",
    "hvac companies st louis",
    "hvac tucson az",
    "hvac companies tucson",
    "hvac tulsa ok",
    "hvac companies tulsa",
    "hvac virginia beach va",
    "hvac companies virginia beach",
    "hvac wichita ks",
    "hvac companies wichita",
    "hvac winston salem nc",
    "hvac companies winston salem",

    # ==========================================================
    # BLOCK 10: ROOFING — EXTENDED SET (~100)
    # ==========================================================
    "roofing company seo services",
    "best roofing seo company",
    "roofing seo tips",
    "roofing seo strategy",
    "roofing company local seo",
    "roofing company google ads",
    "roofing company ppc agency",
    "roofing review management",
    "roofing company reviews",
    "get roofing reviews",
    "roofing brand identity",
    "roofing company logo",
    "roofing company branding ideas",
    "roof installation leads",
    "residential roofing leads",
    "commercial roofing leads",
    "roof replacement leads",
    "roof repair leads",
    "roofing lead gen company",
    "roofing advertising ideas",
    # Roofing city additional
    "roofing companies houston",
    "roofer houston tx",
    "roofing companies austin tx",
    "roofer austin tx",
    "roofing companies san antonio tx",
    "roofer san antonio",
    "roofing companies fort worth tx",
    "roofing companies el paso tx",
    "roofing companies las vegas nv",
    "roofer las vegas",
    "roofing companies denver co",
    "roofer denver",
    "roofing companies phoenix az",
    "roofer phoenix az",
    "roofing companies tucson az",
    "roofing companies albuquerque nm",
    "roofing companies st louis mo",
    "roofing companies kansas city mo",
    "roofing companies oklahoma city",
    "roofing companies tulsa ok",
    "roofing companies memphis tn",
    "roofing companies louisville ky",
    "roofing companies indianapolis in",
    "roofing companies columbus oh",
    "roofing companies cleveland oh",
    "roofing companies cincinnati oh",
    "roofing companies pittsburgh pa",
    "roofing companies richmond va",
    "roofing companies norfolk va",
    "roofing companies virginia beach",
    "roofing companies greensboro nc",
    "roofing companies winston salem",
    "roofing companies columbia sc",
    "roofing companies jacksonville fl",
    "roofing companies miami fl",
    "roofing companies orlando fl",
    "roofing companies tampa fl",
    "roofer tampa fl",
    "roofing companies new orleans la",
    "roofing companies baton rouge la",
    "roofing companies birmingham al",
    "roofing companies minneapolis mn",
    "roofing companies omaha ne",
    "roofing companies wichita ks",
    "roofing companies salt lake city",
    "roofing companies sacramento",
    "roofing companies fresno ca",
    "roofing companies riverside ca",
    "roofing companies portland or",
    "roofing companies seattle wa",

    # ==========================================================
    # BLOCK 11: PLUMBING — EXTENDED SET (~100)
    # ==========================================================
    "plumbing company seo services",
    "best plumbing seo company",
    "plumbing seo tips",
    "plumbing seo strategy",
    "plumbing company local seo",
    "plumbing company google ads",
    "plumbing company ppc agency",
    "plumber review management",
    "plumber reviews online",
    "get plumber reviews",
    "plumbing brand identity",
    "plumbing company logo",
    "plumbing company branding ideas",
    "drain cleaning leads",
    "water heater leads",
    "pipe repair leads",
    "residential plumbing leads",
    "commercial plumbing leads",
    "plumbing lead gen company",
    "plumbing advertising ideas",
    # Plumbing city additional
    "plumber houston tx",
    "plumbing companies houston tx",
    "plumber austin tx",
    "plumbing companies austin",
    "plumber san antonio",
    "plumbing companies san antonio",
    "plumber fort worth tx",
    "plumbing companies fort worth",
    "plumber el paso tx",
    "plumber las vegas nv",
    "plumbing companies las vegas",
    "plumber denver co",
    "plumbing companies denver co",
    "plumber phoenix az",
    "plumbing companies phoenix",
    "plumber tucson az",
    "plumbing companies tucson",
    "plumber albuquerque",
    "plumbing companies albuquerque",
    "plumber st louis mo",
    "plumbing companies st louis",
    "plumber kansas city",
    "plumbing companies kansas city",
    "plumber oklahoma city",
    "plumber tulsa ok",
    "plumber memphis tn",
    "plumbing companies memphis",
    "plumber louisville ky",
    "plumbing companies louisville",
    "plumber indianapolis",
    "plumbing companies indianapolis",
    "plumber columbus ohio",
    "plumbing companies columbus",
    "plumber cleveland oh",
    "plumbing companies cleveland",
    "plumber cincinnati oh",
    "plumbing companies cincinnati",
    "plumber pittsburgh pa",
    "plumbing companies pittsburgh",
    "plumber richmond va",
    "plumber norfolk va",
    "plumber virginia beach",
    "plumber greensboro nc",
    "plumber jacksonville fl",
    "plumbing companies jacksonville",
    "plumber miami fl",
    "plumbing companies miami",
    "plumber orlando fl",
    "plumbing companies orlando",
    "plumber new orleans la",
    "plumber baton rouge la",
    "plumber birmingham al",
    "plumber minneapolis mn",
    "plumbing companies minneapolis",
    "plumber omaha ne",
    "plumber salt lake city",
    "plumbing companies salt lake city",
    "plumber sacramento ca",
    "plumbing companies sacramento",
    "plumber riverside ca",
    "plumber portland or",
    "plumbing companies portland",
    "plumber seattle wa",
    "plumbing companies seattle",

    # ==========================================================
    # BLOCK 12: SEO REPORT / SERP VISIBILITY KEYWORDS (~80)
    # ==========================================================
    "seo report for clients",
    "seo audit report",
    "seo reporting tool",
    "client seo report",
    "white label seo report",
    "serp visibility report",
    "google ranking report",
    "local seo report",
    "seo report template",
    "automated seo report",
    "seo dashboard for clients",
    "seo metrics report",
    "keyword ranking report",
    "rank tracking report",
    "seo progress report",
    # CopperBuilds prospect-related
    "website audit for clients",
    "free website audit",
    "website performance report",
    "seo audit for contractors",
    "free seo audit small business",
    "website grade report",
    "web presence score",
    "local search ranking report",
    "google visibility report",
    "business online visibility",
    # Web agency services
    "web agency services",
    "website management service",
    "monthly website maintenance",
    "website care plan",
    "website support plan",
    "website hosting management",
    "website update service",
    "website redesign service",
    "website rebuild service",
    "website refresh service",
    # CRO/conversion terms
    "cro for small business",
    "conversion rate optimization small business",
    "cro services",
    "landing page optimization",
    "lead gen landing page",
    "high converting website",
    "website redesign for leads",
    "website redesign for conversions",
    "website lead capture",
    "contact form optimization",
    # Analytics + tracking
    "ga4 setup small business",
    "google analytics setup",
    "google tag manager setup",
    "call tracking small business",
    "lead tracking website",
    "website conversion tracking",
    "google ads conversion tracking",
    "facebook pixel setup",
    "website analytics service",
    "marketing analytics small business",
    # Content strategy
    "content marketing small business",
    "blog for small business",
    "blogging for contractors",
    "blogging for seo",
    "content strategy small business",
    "content creation service",
    "seo content writing",
    "blog writing service small business",
    "content marketing agency",
    "small business content agency",
    # Social proof / reviews general
    "online reputation management",
    "reputation management service",
    "review management service",
    "5 star review strategy",
    "get more online reviews",
    "online reviews small business",
    "google rating improvement",
    "yelp review management",
    "review response service",
    "review generation service",

    # ==========================================================
    # BLOCK 13: FINAL FILL — TRADE SERVICES + WEB NICHE (~160)
    # ==========================================================
    # HVAC seasonal + service keywords
    "ac tune up marketing",
    "hvac maintenance marketing",
    "furnace replacement leads",
    "heat pump leads",
    "ductless ac leads",
    "hvac financing leads",
    "hvac service agreement",
    "hvac maintenance plan marketing",
    "commercial hvac marketing",
    "commercial hvac leads",
    "hvac company facebook ads",
    "hvac company instagram",
    "hvac company tiktok",
    "hvac truck wrap design",
    # Roofing service types
    "metal roofing leads",
    "shingle roofing leads",
    "flat roof leads",
    "commercial roofing marketing",
    "commercial roofing seo",
    "roofing company facebook ads",
    "roofing company instagram",
    "roofing door knocking leads",
    "roofing canvassing leads",
    "roof inspector marketing",
    "hail damage roofing leads",
    "wind damage roofing leads",
    "insurance roofing leads",
    # Plumbing service types
    "sewer line repair leads",
    "water heater installation leads",
    "drain cleaning marketing",
    "hydrojetting leads",
    "trenchless pipe repair leads",
    "commercial plumbing marketing",
    "commercial plumbing seo",
    "plumbing company facebook ads",
    "gas line repair leads",
    "bathroom remodel plumbing leads",
    "kitchen plumbing leads",
    "24 hour plumber marketing",
    # Web design comparison terms
    "squarespace vs wordpress small business",
    "wix vs wordpress small business",
    "diy website vs professional",
    "squarespace alternative small business",
    "wordpress website design small business",
    "wordpress vs custom website",
    "website builder vs web designer",
    "diy website for contractor",
    "best website platform small business",
    "cheapest website design",
    # SEO comparison terms
    "local seo vs ppc",
    "seo vs google ads small business",
    "organic seo vs paid ads",
    "local seo vs social media",
    "seo vs facebook ads",
    "google ads vs local seo",
    "seo roi small business",
    "how long does seo take",
    "is seo worth it small business",
    "seo results small business",
    # Near me searches
    "web designer near me",
    "web design company near me",
    "seo company near me",
    "local seo company near me",
    "digital marketing agency near me",
    "marketing agency near me small business",
    "website design near me",
    "seo services near me",
    # Contractor business terms
    "contractor business plan",
    "contractor business tips",
    "how to start contractor business",
    "contractor license marketing",
    "contractor insurance marketing",
    "contractor referral marketing",
    "word of mouth marketing contractor",
    "contractor networking tips",
    "contractor google business profile",
    "contractor google listing",
    "contractor yelp profile",
    "contractor nextdoor profile",
    "home advisor contractor",
    "angi contractor marketing",
    "thumbtack contractor marketing",
    # Specific trade - HVAC equipment types
    "mini split installation marketing",
    "central air installation leads",
    "boiler service marketing",
    "geothermal hvac marketing",
    "smart thermostat installation leads",
    "air quality service marketing",
    "duct cleaning leads",
    "duct cleaning marketing",
    # Specific trade - Plumbing niche
    "water softener leads",
    "water filtration leads",
    "tankless water heater leads",
    "sump pump leads",
    "backflow prevention leads",
    "sprinkler system repair leads",
    "irrigation system marketing",
    # Agency/CopperBuilds positioning
    "web agency for home services",
    "web design for hvac",
    "web design for roofers",
    "web design for plumbers",
    "web design for electricians",
    "web design for landscapers",
    "web design for pest control",
    "website for hvac company",
    "website for roofing company",
    "website for plumbing company",
    "website for electrician",
    "affordable website for contractor",
    "cheap web design for contractor",
    "best web design for home services",
    "top web design agency home services",
    "web design company for contractors",
    # Portfolio / case study terms
    "hvac website examples",
    "roofing website examples",
    "plumbing website examples",
    "contractor website examples",
    "best contractor websites",
    "home service website examples",
    "web design portfolio home services",
    # 34 final fillers — high-value long tail searches
    "hvac company near me marketing",
    "plumber near me marketing",
    "roofer near me marketing",
    "contractor near me seo",
    "best hvac company marketing",
    "best plumber marketing",
    "best roofer marketing",
    "trusted contractor website",
    "licensed contractor website",
    "insured contractor website",
    "fast loading contractor website",
    "mobile friendly contractor website",
    "seo for service area business",
    "service area business seo",
    "multi city seo strategy",
    "seo for multiple locations",
    "local seo multiple cities",
    "rank in multiple cities seo",
    "city page seo strategy",
    "location page seo",
    "service area page seo",
    "hvac city pages seo",
    "roofing city pages seo",
    "plumbing city pages seo",
    "contractor city page seo",
    "city landing pages seo",
    "seo for suburb targeting",
    "neighborhood seo strategy",
    "local landing page seo",
    "local service page seo",
    "google local pack strategy",
    "local pack optimization tips",
    "google 3 pack local business",
    "dominate local pack seo",
]

def fetch_volumes(keywords, location_code=2840):
    url = "https://api.dataforseo.com/v3/keywords_data/google_ads/search_volume/live"
    payload = [{"keywords": keywords, "location_code": location_code, "language_code": "en"}]
    resp = requests.post(url, auth=(USERNAME, PASSWORD), json=payload)
    resp.raise_for_status()
    return resp.json()

def parse_results(data):
    results = []
    for task in data.get('tasks', []):
        cost = task.get('cost', 0)
        print(f"API cost for this task: ${cost:.4f}")
        for item in task.get('result', []):
            results.append({
                'keyword': item.get('keyword'),
                'volume': item.get('search_volume') or 0,
                'competition': item.get('competition') or 'n/a',
                'cpc': item.get('cpc') or 0,
            })
    return sorted(results, key=lambda x: x['volume'], reverse=True)

if __name__ == '__main__':
    total = len(KEYWORDS)
    print(f"Sending {total} keywords in one bulk request...")

    data = fetch_volumes(KEYWORDS)
    results = parse_results(data)

    print(f"\n{'Keyword':<52} {'Volume':>8} {'Competition':<14} {'CPC':>7}")
    print("-" * 85)
    for r in results:
        if r['volume'] > 0:
            cpc = f"${r['cpc']:.2f}" if r['cpc'] else 'n/a'
            print(f"{r['keyword']:<52} {r['volume']:>8,} {r['competition']:<14} {cpc:>7}")

    zero_count = sum(1 for r in results if r['volume'] == 0)
    print(f"\n--- Zero volume ({zero_count} keywords) ---")
    for r in results:
        if r['volume'] == 0:
            print(f"  {r['keyword']}")

    out = os.path.join(os.path.dirname(__file__), 'kw_database.json')
    with open(out, 'w') as f:
        json.dump(results, f, indent=2)
    print(f"\nFull database saved to .tmp/kw_database.json ({total} keywords)")
